name: .NET Framework

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-version: latest

    - name: Restore dependencies
      run: nuget restore JRBAWebApplication2.sln

    - name: Build
      run: msbuild JRBAWebApplication2.sln /p:Configuration=Release

    - name: Run Unit Tests
      run: dotnet test --filter Category=Unit

    - name: Run Integration Tests
      run: dotnet test --filter Category=Integration

    - name: Run Regression Tests
      run: dotnet test --filter Category=Regression

    - name: Run Functional Tests
      run: dotnet test --filter Category=Functional
