name: .NET Framework

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-version: latest

    - name: Restore dependencies
      run: nuget restore JRBAWebApplication2.sln

    - name: Build
      run: msbuild JRBAWebApplication2.sln /p:Configuration=Release

    - name: Run Unit Tests
      run: |
       cd JRBAWebApplication2.Test nuget install MSTest.TestFramework -Version 2.1.2 -OutputDirectory packages
       nuget install MSTest.TestAdapter -Version 2.1.2 -OutputDirectory packages
       packages\MSTest.TestAdapter.2.1.2\build_common\mstest.console.exe JRBAWebApplication2.Tests.dll

      shell: cmd

    - name: Run Integration Tests
      run: |
        # Add commands to run integration tests if needed
      shell: bash

    - name: Run Regression Tests
      run: |
        # Add commands to run regression tests if needed
      shell: bash

    - name: Run Functional Tests
      run: |
        # Add commands to run functional tests if needed
      shell: bash
