name: .NET Framework

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2  # Use the setup-msbuild action
      with:
        msbuild-version: latest  # You can specify a specific version if needed

    - name: Restore dependencies
      run: nuget restore JRBAWebApplication2.sln

    - name: Build
      run: msbuild JRBAWebApplication2.sln /p:Configuration=Release

    - name: Test
      run: |
        # Run your tests here if you have a specific testing framework.
        # Example for MSTest:
        # vstest.console.exe YourTestProject.dll
    ##  run: vstest.console.exe Test.dll
